name: cd-build

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: Build
      run: |
        msbuild /restore /t:Build,Pack src/BlazorWebView.WinUI/BlazorWebView.WinUI3.csproj /p:Configuration=Release /p:PackageVersion=${{ steps.version.outputs.version-without-v }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NuGet Packages
        path: artifacts/NuGet/Release 
        
    - name: Push to NuGet
      run: |
        dotnet nuget push artifacts\NuGet\Release\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.org
        dotnet nuget push artifacts\NuGet\Release\*.snupkg -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.org
