name: ci-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ src/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: |
        msbuild /restore /t:Build,Pack src/BlazorWebView.WinUI3/BlazorWebView.WinUI3.csproj /p:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NuGet Packages
        path: \**\artifacts\NuGet\Release
